version: "3.9"
services:
  nodejs:
    container_name: "nodejs"
    build:
      dockerfile: "./container/nodejs/Dockerfile"
    ports:
      - "5555:5555"
    tty: true
    volumes:
      - "./app:/app"
      - "./work:/work"
  db:
    container_name: "db"
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - "./db1:/var/lib/postgresql/data"
      - "./work:/work"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
      - "./work:/work"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
