version: "3.9"
services:
  nodejs:
    container_name: "nodejs"
    build:
      dockerfile: "./container/nodejs/Dockerfile"
    ports:
      - "5173:5173"
    volumes:
      - "./app:/app"
      - "./work:/work"
  db:
    container_name: "db"
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - "./db1:/var/lib/postgresql/data"
      - "./work:/work"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
